/**
 * Stable error codes for the Expense Tracker product, per
 * specs/001-local-expense-tracker/contracts/api.md.
 */

/** Error families required by the application contract. */
export const ERROR_CODES = {
  // Vault lifecycle
  VAULT_INVALID: 'VAULT_INVALID',
  VAULT_VERSION_UNSUPPORTED: 'VAULT_VERSION_UNSUPPORTED',
  VAULT_DECRYPT_FAILED: 'VAULT_DECRYPT_FAILED',
  VAULT_EXPORT_FAILED: 'VAULT_EXPORT_FAILED',
  // Pairing
  PAIRING_EXPIRED: 'PAIRING_EXPIRED',
  PAIRING_REJECTED: 'PAIRING_REJECTED',
  PAIRING_REVOKED: 'PAIRING_REVOKED',
  PAIRING_KEY_MISMATCH: 'PAIRING_KEY_MISMATCH',
  // Synchronization
  SYNC_DISCONNECTED: 'SYNC_DISCONNECTED',
  SYNC_RETRYABLE: 'SYNC_RETRYABLE',
  SYNC_MUTATION_INVALID: 'SYNC_MUTATION_INVALID',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  SYNC_BACKLOG_PENDING: 'SYNC_BACKLOG_PENDING',
  SYNC_BATCH_DUPLICATE_SAFE: 'SYNC_BATCH_DUPLICATE_SAFE',
  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CURRENCY_REQUIRED: 'CURRENCY_REQUIRED',
  AMOUNT_INVALID: 'AMOUNT_INVALID',
  DATE_INVALID: 'DATE_INVALID',
  // Import
  IMPORT_UNSUPPORTED_TYPE: 'IMPORT_UNSUPPORTED_TYPE',
  IMPORT_TOO_LARGE: 'IMPORT_TOO_LARGE',
  IMPORT_EMPTY: 'IMPORT_EMPTY',
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  IMPORT_PDF_ENCRYPTED: 'IMPORT_PDF_ENCRYPTED',
  IMPORT_PDF_IMAGE_ONLY: 'IMPORT_PDF_IMAGE_ONLY',
  IMPORT_PDF_UNSUPPORTED_LAYOUT: 'IMPORT_PDF_UNSUPPORTED_LAYOUT',
  IMPORT_ROW_AMBIGUOUS: 'IMPORT_ROW_AMBIGUOUS',
  IMPORT_DUPLICATE_CANDIDATE: 'IMPORT_DUPLICATE_CANDIDATE',
  IMPORT_COMMIT_INCOMPLETE: 'IMPORT_COMMIT_INCOMPLETE',
  // Destructive actions
  DELETE_CONFIRMATION_REQUIRED: 'DELETE_CONFIRMATION_REQUIRED',
  CLEAR_LOCAL_DATA_CONFIRMATION_REQUIRED: 'CLEAR_LOCAL_DATA_CONFIRMATION_REQUIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Stable, machine-readable row-level diagnostic codes. Unlike top-level error
 * codes these attach to a specific source row so the UI can group and explain
 * them without ever silently discarding financial data.
 */
export const DIAGNOSTIC_CODES = {
  ROW_MISSING_DATE: 'ROW_MISSING_DATE',
  ROW_INVALID_DATE: 'ROW_INVALID_DATE',
  ROW_MISSING_AMOUNT: 'ROW_MISSING_AMOUNT',
  ROW_AMBIGUOUS_AMOUNT: 'ROW_AMBIGUOUS_AMOUNT',
  ROW_INVALID_AMOUNT: 'ROW_INVALID_AMOUNT',
  ROW_MISSING_MERCHANT: 'ROW_MISSING_MERCHANT',
  ROW_UNRECOGNIZED_COLUMNS: 'ROW_UNRECOGNIZED_COLUMNS',
  ROW_DUPLICATE_CANDIDATE: 'ROW_DUPLICATE_CANDIDATE',
  ROW_UNPARSEABLE: 'ROW_UNPARSEABLE',
  ROW_BLANK: 'ROW_BLANK',
  ROW_UNSUPPORTED: 'ROW_UNSUPPORTED',
} as const;

export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[keyof typeof DIAGNOSTIC_CODES];

/** Grouping used for UI filters (attention vs accepted rows). */
export type DiagnosticSeverity = 'info' | 'warning' | 'error';
