/**
 * iOS design-token emission (T008). Emits a Swift source file with semantic
 * Color/UIColor constants that map one-to-one to the web semantic tokens so the
 * two platforms share a visual family while remaining platform-native.
 */

import { SEMANTIC_TOKENS, SPACING, RADIUS, TYPE_SCALE } from '../web/tokens';

export function iosDesignTokensSwift(): string {
  const colors = Object.entries(SEMANTIC_TOKENS)
    .map(([name, hex]) => `    static let ${swiftName(name)} = Color(hex: 0x${hex.replace('#', '')})`)
    .join('\n');

  const spacing = Object.entries(SPACING)
    .map(([name, value]) => `    static let spacing${cap(name)} = CGFloat(${value})`)
    .join('\n');

  const radius = Object.entries(RADIUS)
    .map(([name, value]) => `    static let radius${cap(name)} = CGFloat(${value})`)
    .join('\n');

  return `// Generated by @expense-tracker/design-tokens (T008). Do not edit by hand.
import SwiftUI
import UIKit

extension Color {
  /// Expandable hex color initializer (iOS 16 compatible).
  init(hex: UInt32, opacity: Double = 1) {
    self.init(
      .sRGB,
      red: Double((hex >> 16) & 0xFF) / 255,
      green: Double((hex >> 8) & 0xFF) / 255,
      blue: Double(hex & 0xFF) / 255,
      opacity: opacity
    )
  }
}

/// Semantic design tokens shared with the web client vocabulary.
public enum ExpenseTrackerDesignTokens {
${colors}
${spacing}
${radius}

  public static let displayFontSize = CGFloat(${TYPE_SCALE.display.size})
  public static let heading1FontSize = CGFloat(${TYPE_SCALE.heading1.size})
  public static let heading2FontSize = CGFloat(${TYPE_SCALE.heading2.size})
  public static let bodyFontSize = CGFloat(${TYPE_SCALE.body.size})
  public static let smallFontSize = CGFloat(${TYPE_SCALE.small.size})
  public static let touchTargetMinimum = CGFloat(44)
}
`;
}

function swiftName(camelCase: string): string {
  return camelCase.charAt(0).toUpperCase() + camelCase.slice(1);
}

function cap(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
